### ISSUE TITLE
1. Govt. ID creation Logic

### ISSUE THREAD

**Issue by pacckishor** [collecteddoc/All-Cadre#1]
- Govt.ID(12digit): For 12 digits ID creation there is a specific rules, from left 2 digits cadre code, 4 digits appointment year, 6 digits existing Present Id or PSC merit list , if any cadre office has  previous govt id then present govt id then present id is preferable other wise if created by PSC merit list.
- Example:012019700009 here 01=Cadre Code, 2019=Appointment Year (come from Appointment GO Date), 700009=Present ID or  
012019000005 here 01=Cadre Code, 2019=Appointment Year (come from Appointment GO Date), 000005=PSC Merit Serial Number
- if Present ID black/Empty then take it from PSC Merit Serial Number.
- If "Sub Cadre" is exist for any employee, then right side 5th and 6th digit should be replaced by "Sub Cadre code", Otherwise right side 5th and 6th digit should be replaced by "00". It is noted that "Cadre" and "Sub Cadre" code should be 2 digit.

**Comment by mypayroll** [comment]
It's done
