### ISSUE TITLE
10. In PMIS tab changes in all pages

### ISSUE THREAD

**Issue by aminshaka** [collecteddoc/All-Cadre#10]
-There will be 2 tab. e.g. List & Create.
-when user will click on the "List" tab then page will be refreshed and tab name will be changed to "List" & "Create".
-"Back" button will be added in the create/edit page. when click on the "Back" button then page will be refreshed and tab name will be changed to "List" & "Create".
-When user will click on the "Edit" button in the list then "Create" tab title will be changed to "Edit" tab title.
-In Edit mode, "Save" button will be changed to "Update" button.

![image](https://user-images.githubusercontent.com/52271735/60955475-ba38a200-a322-11e9-837e-fc2fb876d34b.png)

**Comment by mypayroll** [comment]
It's done
