### ISSUE TITLE
16. Acknowledgement of All Cadre PMIS Registration.

### ISSUE THREAD

**Issue by pacckishor** [collecteddoc/All-Cadre#16]
**1. After click on the "Registration" button there should have a warning message like this:**
![image](https://user-images.githubusercontent.com/46019822/60958985-346c2500-a329-11e9-9481-b0f1d133aa9e.png)

**2. Registration successful message should be like this**
![image](https://user-images.githubusercontent.com/46019822/60958970-2f0eda80-a329-11e9-9fec-bff232daa639.png)

**3. Registration confirmation email body should be like this:**
![image](https://user-images.githubusercontent.com/52484873/60958545-59ac6380-a328-11e9-995f-ca4d744c3f9f.png)

1. by default email:pmis@mopa.gov.bd

**Comment by mypayroll** [comment]
It's done
