### ISSUE TITLE
19. Registration approval page is missing

### ISSUE THREAD

**Issue by collecteddoc** [collecteddoc/All-Cadre#19]
Please go to the page 60 in all cadre SRS for page design. After approval user will be notified by email. 
- Registration (both create and edit), "PSC merit sl no" should be mandatory field. 
-  Registration (edit), "PSC merit sl no" should be mandatory. If user input "Present Id" then "Gov Id" will be updated by "Present Id" instead of "PSC merit sl no".
- If "Sub Cadre" is exist for any employee, then right side 5th and 6th digit should be replaced by "Sub Cadre code", Otherwise right side 5th and 6th digit should be replaced by "00". It is noted that "Cadre" and "Sub Cadre" code should be 2 digit.

![image](https://user-images.githubusercontent.com/46019822/61269827-931a1e80-a7c1-11e9-93b8-d93aa24b84fb.png)

**Comment by mypayroll** [comment]
It's done
