### ISSUE TITLE
20 .In "Sub Cadre" page, Add another field named "Code" which should allow only 2 digit number.

### ISSUE THREAD

**Issue by pacckishor** [collecteddoc/All-Cadre#20]
- add new field "Code"
- "Cadre master name" combobox should be top of the fields. 

![image](https://user-images.githubusercontent.com/52484873/61287709-4e08e300-a7e7-11e9-8e01-d61ccd901286.png)

**Comment by mypayroll** [comment]
It's Done

**Comment by mypayroll** [comment]
It's done
