### ISSUE TITLE
22. In Information Entry => Every pages, Pic is not displaying.

### ISSUE THREAD

**Issue by collecteddoc** [collecteddoc/All-Cadre#22]
![image](https://user-images.githubusercontent.com/46019822/61587942-3c438900-abb5-11e9-8fc1-51f3d8e312e8.png)

**Comment by mypayroll** [comment]
![image](https://user-images.githubusercontent.com/52411235/67087507-b1c4f280-f1c0-11e9-9de8-cd571d12d19a.png)

No it's working properly.
