### ISSUE TITLE
26. In Information Entry => Education list page, "Search by Gov.Id" is not working. 

### ISSUE THREAD

**Issue by collecteddoc** [collecteddoc/All-Cadre#26]
![image](https://user-images.githubusercontent.com/46019822/61588218-58492980-abb9-11e9-9de3-866efaedb605.png)

**Comment by mypayroll** [comment]
It's working properly.

![image](https://user-images.githubusercontent.com/52411235/67088043-cce43200-f1c1-11e9-848d-fb6e20d60c0d.png)
