### ISSUE TITLE
27. In Information Entry => (Foreign travel information/ foreign travel entry) page, there are problems.

### ISSUE THREAD

**Issue by collecteddoc** [collecteddoc/All-Cadre#27]
- Duplicate "Gov Id" should not be allowed.
-  SPDS, LPSD link is not working. 
-  Spelling mistake. It should be "SPDS" instead of "SPDB".

![image](https://user-images.githubusercontent.com/46019822/61588239-b970fd00-abb9-11e9-9c0b-9c3349f5229c.png)

**Comment by mypayroll** [comment]
IT's resolved.
