### ISSUE TITLE
28. Message text should be proper. 

### ISSUE THREAD

**Issue by collecteddoc** [collecteddoc/All-Cadre#28]
- When saving any record display "Record save successfully".
- When update any record display "Record updated successfully".
- When deleting any record display "Record deleted successfully".
- When validating any record display "Record validated successfully".
- When rejecting any record display "Record rejected successfully".

**Comment by mypayroll** [comment]
![image](https://user-images.githubusercontent.com/52411235/67088285-61e72b00-f1c2-11e9-999e-663f8f1fd7bd.png)

It's done.
