### ISSUE TITLE
3. replace Designation, Organization and SingUp

### ISSUE THREAD

**Issue by pacckishor** [collecteddoc/All-Cadre#3]
![image](https://user-images.githubusercontent.com/52484873/60800164-82045880-a196-11e9-8db0-7e2cd29acaf5.png)
3. replace by 
![image](https://user-images.githubusercontent.com/52484873/60800290-c859b780-a196-11e9-8c13-14b7d24bc830.png)
4. replace by 
![image](https://user-images.githubusercontent.com/52484873/60800413-f8a15600-a196-11e9-8d72-b429a901534c.png)

**Comment by mypayroll** [comment]
It's done
