### ISSUE TITLE
30. In Information Entry => Publication page, Date is now showing properly.

### ISSUE THREAD

**Issue by collecteddoc** [collecteddoc/All-Cadre#30]
![image](https://user-images.githubusercontent.com/46019822/61589884-4758e200-abd2-11e9-80f9-26016eaf2b1c.png)

**Comment by mypayroll** [comment]
![image](https://user-images.githubusercontent.com/52411235/67088925-0158ed80-f1c4-11e9-990e-8f35e7738cad.png)

It's done.
