### ISSUE TITLE
32. In Information Entry => Other Service, Date is not showing properly.

### ISSUE THREAD

**Issue by collecteddoc** [collecteddoc/All-Cadre#32]
![image](https://user-images.githubusercontent.com/46019822/61590046-8d16aa00-abd4-11e9-84b3-7e81bfeee2d6.png)

**Comment by mypayroll** [comment]
![image](https://user-images.githubusercontent.com/52411235/67091083-58ad8c80-f1c9-11e9-9e17-46796592c827.png)
