### ISSUE TITLE
34. In Information entry => Language proficiency information page, data is not saving.

### ISSUE THREAD

**Issue by collecteddoc** [collecteddoc/All-Cadre#34]
![image](https://user-images.githubusercontent.com/46019822/61590113-8f2d3880-abd5-11e9-8b68-00a7d04e075b.png)

**Comment by mypayroll** [comment]
![image](https://user-images.githubusercontent.com/52411235/67092896-0de24380-f1ce-11e9-9d69-b5c17b947e4f.png)

It's working properly.
