### ISSUE TITLE
36. In Edit/Update mode, "Search" button to search by gov Id should be disabled/invisibled.

### ISSUE THREAD

**Issue by collecteddoc** [collecteddoc/All-Cadre#36]

**Comment by mypayroll** [comment]
![Uploading image.png…]()

**Comment by mypayroll** [comment]
![image](https://user-images.githubusercontent.com/52411235/67093232-c7411900-f1ce-11e9-8b79-1db6d129365c.png)

It's done now.

**Comment by mypayroll** [comment]
It's done.
