### ISSUE TITLE
37. Changes in registration page

### ISSUE THREAD

**Issue by collecteddoc** [collecteddoc/All-Cadre#37]
Registration Pending => View is not working. In view page Admin user will get "Edit", "Validate", "Reject" button. 
Registration Email subject is not correct.
After Approval user will get notification. The body shall be provided by Md.Zakir (Stakeholder). 
Password should be datebyBirth. Format should be ddmmyyyy e.g. 01012019
Gov.Id should be 12 digits. User will login using his/her 12 digits GovId and Password (Date of Birth e.g. ddmmyyyy)
Remove Id from email body.
GovId and Email should be Unique.

**Comment by mypayroll** [comment]
It's Done.
