### ISSUE TITLE
38. Need to create 2 separate UI for admin and sub-admin

### ISSUE THREAD

**Issue by collecteddoc** [collecteddoc/All-Cadre#38]
![Sub Admin](https://user-images.githubusercontent.com/46019822/62124045-1459d100-b2eb-11e9-8a2d-c2f28f691a3f.png)
![Admin](https://user-images.githubusercontent.com/46019822/62124046-14f26780-b2eb-11e9-944e-3e8767b68231.png)

**Comment by mypayroll** [comment]
It's Done.
