### ISSUE TITLE
39. Changes in registration

### ISSUE THREAD

**Issue by collecteddoc** [collecteddoc/All-Cadre#39]
All cadre feedbacks:
1. "Cadre Name" & "Ministry Name" should be matched, otherwise after submiting info it will show message "You are not eligibible for registration.".

2. Registration Email subject is not correct. Told Mohit last day. Issue 16 not implemented. User should not get gov.Id before approval. remove it from email.

3. In registration pending => view, there should have "Approve" button. remove "Update" button.

4. In registration pending, there should have "Edit" icon. In "Edit" mode, there should have "Update" button.

5. In both Edit and View mode, user can download/view attachment.

**Comment by mypayroll** [comment]
All requirements are successfully achieved.
