### ISSUE TITLE
42. In registration page, "cadre name' and "ministry name" should be matched when user click on the "Request for registration" button, otherwise validation msg should be displayed as "Your selected ministry is not correct"

### ISSUE THREAD

**Issue by pacckishor** [collecteddoc/All-Cadre#42]
- After selecting "Cadre Name", "Ministry Name" should not be auto selected.

- In registration page when user click on the "Request for registration" button,, "cadre name' and "ministry name" should be matched, otherwise validation msg should be displayed as "Your selected ministry is not correct"

 
![image](https://user-images.githubusercontent.com/52484873/64074738-1ab7e000-ccd1-11e9-91e8-6b21e4728bfd.png)

**Comment by mypayroll** [comment]
It's resolved and made according to requirements.
