### ISSUE TITLE
45. Registration Pending

### ISSUE THREAD

**Issue by pacckishor** [collecteddoc/All-Cadre#45]
-Agriculture Cadre Admin: Can not see the Registration Pending List

![image](https://user-images.githubusercontent.com/52484873/64074992-32dd2e80-ccd4-11e9-9033-63a30c7f62b5.png)

**Comment by mypayroll** [comment]
![image](https://user-images.githubusercontent.com/52411235/67097672-3cfdb280-f1d8-11e9-9c20-a94943a78cd5.png)

no it's there.
